### ISSUE TITLE
Google tasks doesn't work properly in Calendar tab

### ISSUE THREAD

**Issue by gpadmos** [Mossop/WebAppTabs#44]
Selecting the "Tasks" calendar in Google Calendar opens up a sidebar that should allows users to manage Google tasks.  No Thunderbird web tab add-on I've found has been able to get that feature to work.  I tried WebApp Tabs hoping that it might work, but still the same symptoms:  the frame opens on the side with a Tasks heading, but there is zero functionality.  It is difficult to express how much joy it would bring me (and many others) if someone were able to get that to work!

**Comment by Mossop** [comment]
Thanks for the report, I think I can see the cause of the problem already, there is an iframe there with its src attribute set to a javascript: url. This might be tricky to solve as Thunderbird defaults to ignoring javascript urls, I've already had to hack around this for a few other cases though so I might be able to solve this.

**Comment by gpadmos** [comment]
That's wonderful to hear, Dave.  I do hope you are able to figure it 
out.  If you do, please let me know to which address I can send a batch 
of chocolate chip cookies!

Grant

**Comment by Mossop** [comment]
I've just landed a fix for this and it should be in the next release. If you want to test an experimental version (should be pretty safe) to see if it works ok for you then I've uploaded one here: https://github.com/downloads/Mossop/WebAppTabs/WebAppTabs-3.0a1.xpi

**Comment by gpadmos** [comment]
I installed the experimental version and it doesn't seem to be making a 
difference.  Is there any debugging information I can give you?  I am 
running Thunderbird 11.0.1 on XP.

**Comment by Mossop** [comment]
First question is what address you're using for the calendar webapp? If it isn't "www.google.com/calendar" then try that, it should work even if you're using google apps for your domain.

If that doesn't help then make sure the tasks sidebar is closed, close the calendar tab and then in Thunderbirds config manager create the pref "extensions.webapptabs.loglevel" as an integer pref and set it to 0. Then disable then enable the add-on, open the calendar tab and wait for everything to load. Click on tasks and then look in Thunderbird's error console. There should be a message somewhere near the end starting with nsMsgContentPolicy. What does it say?

**Comment by gpadmos** [comment]
Still no luck using that address.  Followed the procedure, loaded the
calendar, cleared the error console.  When I click tasks, the only got
errors are of the type:

Warning: Error in parsing value for 'background'.  Declaration dropped.
Source File: https://www.google.com/calendar/render
Line: 0

I'm pretty sure those errors were occurring when using other browser tab
extensions as well.

On Mon, Apr 2, 2012 at 11:58 AM, Dave Townsend <
reply@reply.github.com

**Comment by Mossop** [comment]
I'm sorry, looks like I uploaded the wrong file for testing. I've replaced it with the correct one so try using that and see if it works now.

**Comment by gpadmos** [comment]
```
SUCCESS!
With new file, error console listed message (which seems to be good
news):nsMsgContentPolicy: Accepting javascript protocol load
  for https://www.google.com/calendar/render

On 4/2/2012 2:27 PM, Dave Townsend wrote:

  I'm sorry, looks like I uploaded the wrong file for testing. I've replaced it with the correct one so try using that and see if it works now.
```

---

**Comment by Mossop** [comment]
Excellent, you can probably reset that logging pref you created now.
