### ISSUE TITLE
Google task

### ISSUE THREAD

**Issue by patapouf69** [Mossop/WebAppTabs#46]
Hi, I'm trying to add google task in WebAppTabs but the following link does not work inside the plugin.

https://mail.google.com/tasks/ig

Is there any way to get google Task inside the plugin?

thank you

**Comment by Mossop** [comment]
I believe that this was fixed already with issue #44. You can test with this experimental version if you wish https://github.com/downloads/Mossop/WebAppTabs/WebAppTabs-3.0a1.xpi, I'm hoping to do an updated release soon.

**Comment by patapouf69** [comment]
Very good,

Now ia have my google task inside Thunderbird. Your vrsion is working like a charm

Thank you
