### ISSUE TITLE
Google tasks webapp does not work

### ISSUE THREAD

**Issue by ghost** [Mossop/WebAppTabs#53]
Hey!

I added google tasks webapp but nothing appears.
both of the following links worked in Firefox but not in WebApp Tabs.

https://mail.google.com/tasks/canvas
https://mail.google.com/tasks/ig

Is there something to do about this?
thanks

**Comment by Mossop** [comment]
This is a duplicate of issue #46, I really must release the updated version.

**Comment by bets** [comment]
I'd like that :)
