### ISSUE TITLE
How to get Mightytext app to work

### ISSUE THREAD

**Issue by ghost** [Mossop/WebAppTabs#54]
Hi!

I use an Android app called Mightytext so I can send and receive text messages through the computer browser and not the phone.
It works in Firefox. 
when I try to open it in WebAppTabs I get "Logging in to MightyText with your Google account . . " which is ok but that message stays and on the tab button it says "Loading..." and the app is opened in Firefox and not in TB.

The webapp:
https://mightytext.net/app/
The Android app:
https://play.google.com/store/apps/details?id=com.texty.sms&hl=en
The website:
http://mightytext.net/

What can I do?
Thanks!

**Comment by Mossop** [comment]
This is issue #43, the website redirects you to a google site for login which the extension thinks isn't part of the webapp.
