### ISSUE TITLE
from Barry - using WebApp tabs in Postbox

### ISSUE THREAD

**Issue by barryhill** [Mossop/WebAppTabs#56]
Hi

I am using and really appreciating the Web App Tabs extension. 

I notice that Thunderbird is no longer being developed by Mozilla, and that Postbox is being promoted in its wake.  I have installed Postbox and see that many Thunderbird extensions are already ported over to Postbox, most of the popular ones for sure such as Lightning, ReminderFox etc.

However, I see your extension has yet to be ported over?  I did try to change the rdf file as an experiment to see if I could make it work, but unsuccessfully.  There must be a little more to do to make it compatible with Postbox?

I have gone back to Thunderbird as a result, as I cannot really do without your Web App Tabs extension.  But feel jittery about staying with a potentially unstable or unsafe Thunderbird email client?

Do you have plans to port your BCC extension over to Postbox?

thanks

Barry

---

I value my online privacy and security.  If you want to send me a mailshot
please use the bcc: box and treat all my emails as confidential to you

Barry Hill (Achintya)
61 Quantock Rd
Bristol
Windmill Hill
BS3 4PQ

mob:   07957 340689
tel:       0117 9531106
email:  barrydhill@blueyonder.co.uk

---

**Comment by Mossop** [comment]
Sorry but I don't use Postbox myself and I have no plans to work on porting my extension to it. I'd be happy to accept patches to support it though.
