### ISSUE TITLE
Install Error - "does not match addon expected"

### ISSUE THREAD

**Issue by BurkeKnight** [Mossop/WebAppTabs#61]
When tried to install WebApp Tabs 2.1.1-let-fixed on Thunderbird 38.5.0 I got a red bar with a message I never saw before in any Mozilla product.

"The add-on from addons.mozilla.org could not be installed because it does not match the add-on Thunderbird expected."

Any ideas on what is wrong?

**Comment by Mossop** [comment]
This is an AMO issue. Normally it is fixed quickly but if it persists please report it to them.
