### ISSUE TITLE
Connection Issues

### ISSUE THREAD

**Issue by htho** [Mossop/WebAppTabs#62]
Hi,

I am using toggl (time tracking) and slack (team collaboration) with WebAppTabs.

Both apps somehow "lose" their connection.

In toggl it runs fine for some hours, but then the timer just continues running and an error states, that it cannot sync with the server. When stopping the timer in this state, this event is not sent to the server. When restarting, the timer still is running.

In slack, I can login and see the menu on the left, but the mainwindow just says it is reconnecting. After the reconnection fails, I get this error message:

> Apologies, we're having some trouble with your web socket connection.
> 
> We've seen this problem clear up with a restart of your browser, a solution which we suggest to you now only with great regret and self-loathing.

Of course a restart does not help.

Best regards, and I hope there is still some life in this great pluging.

htho

**Comment by Mossop** [comment]
Sorry, this add-on is no longer maintained. It is possible that Thunderbird doesn't support websockets.
