### ISSUE TITLE
Page not loading after login

### ISSUE THREAD

**Issue by Sungod3000** [Mossop/WebAppTabs#64]
Hi,

I have tested a number of browsers for firefox but i cant seem to log in to websites in any of them.

While facebook works im trying to get into trello.com but after I log in I get an almost blank page and on the bottom it says "Having trouble logging in...?" I read somewhere that one needs a special build of thunderbird for the log in to work correctly could that help here as well?

Cheers
![2017-01-01 13_15_03-trello - mozilla thunderbird](https://cloud.githubusercontent.com/assets/6022555/21581153/55ac87bc-d024-11e6-927e-89e39c9e459c.jpg)

**Comment by Mossop** [comment]
This add-on is completely unmaintained and unsupported.
